### PR TITLE
Internet connection error reporting

### PR DESCRIPTION
**Pull request by timmattison**
**Description of changes:**
This change will report if there are Internet connectivity issues when attempting to update the connectivity info

**Why is this change necessary:**
A customer asked about their Greengrass V2 policy and referenced this error message. It turns out that the real cause of the issue is that the Internet connection was down and an UnknownHostException was thrown. This change adds a new error message that will tell customers that their Internet connection is down so that they won't immediately jump to debugging their IAM policies.

**Any additional information or context required to review the change:**
I'm an AWS employee

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jbutler** [comment]
Thanks for the PR, Tim. LGTM, though we can't merge til the line length build warnings are resolved. If you update we can merge, otherwise we're happy to take over as well.

**Comment by timmattison** [comment]
Got it. Thanks for the quick reply. Let's see if this does it.

**Comment by timmattison** [comment]
One more time...

**Comment by timmattison** [comment]
Fixed a busted test

**Review by jbutler — APPROVED** [review]

**Pull request merged**
